kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: todo-cluster
nodes:
 -  role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 8080
      - containerPort: 443
        hostPort: 8443
